<?php

declare(strict_types=1);

namespace ChristianBrown\EBay\Browse\Tests\Model;

use ChristianBrown\EBay\Browse\Model\CategoryInterface;
use ChristianBrown\EBay\Browse\Model\CompatibilityPropertyInterface;
use ChristianBrown\EBay\Browse\Model\ConvertedAmountInterface;
use ChristianBrown\EBay\Browse\Model\ImageInterface;
use ChristianBrown\EBay\Browse\Model\ItemLocationInterface;
use ChristianBrown\EBay\Browse\Model\ItemSummary;
use ChristianBrown\EBay\Browse\Model\MarketingPriceInterface;
use ChristianBrown\EBay\Browse\Model\PickupOptionSummaryInterface;
use ChristianBrown\EBay\Browse\Model\SellerInterface;
use ChristianBrown\EBay\Browse\Model\ShippingOptionInterface;
use ChristianBrown\EBay\Browse\Model\TargetLocationInterface;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(ItemSummary::class)]
final class ItemSummaryTest extends TestCase
{
    public function test(): void
    {
        $additionalImages = [self::createStub(ImageInterface::class)];
        $buyingOptions = ['s'];
        $categories = [self::createStub(CategoryInterface::class)];
        $compatibilityProperties = [self::createStub(CompatibilityPropertyInterface::class)];
        $currentBidPrice = self::createStub(ConvertedAmountInterface::class);
        $distanceFromPickupLocation = self::createStub(TargetLocationInterface::class);
        $image = self::createStub(ImageInterface::class);
        $itemLocation = self::createStub(ItemLocationInterface::class);
        $leafCategoryIds = ['s'];
        $marketingPrice = self::createStub(MarketingPriceInterface::class);
        $pickupOptions = [self::createStub(PickupOptionSummaryInterface::class)];
        $price = self::createStub(ConvertedAmountInterface::class);
        $qualifiedPrograms = ['s'];
        $seller = self::createStub(SellerInterface::class);
        $shippingOptions = [self::createStub(ShippingOptionInterface::class)];
        $thumbnailImages = [self::createStub(ImageInterface::class)];
        $unitPrice = self::createStub(ConvertedAmountInterface::class);

        $itemSummary = new ItemSummary('val_itemId');
        self::assertSame('val_itemId', $itemSummary->getItemId());
        self::assertSame([], $itemSummary->getAdditionalImages());
        self::assertNull($itemSummary->getAdultOnly());
        self::assertNull($itemSummary->getAvailableCoupons());
        self::assertNull($itemSummary->getBidCount());
        self::assertSame([], $itemSummary->getBuyingOptions());
        self::assertSame([], $itemSummary->getCategories());
        self::assertNull($itemSummary->getCompatibilityMatch());
        self::assertSame([], $itemSummary->getCompatibilityProperties());
        self::assertNull($itemSummary->getCondition());
        self::assertNull($itemSummary->getConditionId());
        self::assertNull($itemSummary->getCurrentBidPrice());
        self::assertNull($itemSummary->getDistanceFromPickupLocation());
        self::assertNull($itemSummary->getEnergyEfficiencyClass());
        self::assertNull($itemSummary->getEpid());
        self::assertNull($itemSummary->getImage());
        self::assertNull($itemSummary->getItemAffiliateWebUrl());
        self::assertNull($itemSummary->getItemCreationDate());
        self::assertNull($itemSummary->getItemEndDate());
        self::assertNull($itemSummary->getItemGroupHref());
        self::assertNull($itemSummary->getItemGroupType());
        self::assertNull($itemSummary->getItemHref());
        self::assertNull($itemSummary->getItemLocation());
        self::assertNull($itemSummary->getItemOriginDate());
        self::assertNull($itemSummary->getItemWebUrl());
        self::assertSame([], $itemSummary->getLeafCategoryIds());
        self::assertNull($itemSummary->getLegacyItemId());
        self::assertNull($itemSummary->getListingMarketplaceId());
        self::assertNull($itemSummary->getMarketingPrice());
        self::assertSame([], $itemSummary->getPickupOptions());
        self::assertNull($itemSummary->getPrice());
        self::assertNull($itemSummary->getPriceDisplayCondition());
        self::assertNull($itemSummary->getPriorityListing());
        self::assertSame([], $itemSummary->getQualifiedPrograms());
        self::assertNull($itemSummary->getSeller());
        self::assertSame([], $itemSummary->getShippingOptions());
        self::assertNull($itemSummary->getShortDescription());
        self::assertSame([], $itemSummary->getThumbnailImages());
        self::assertNull($itemSummary->getTitle());
        self::assertNull($itemSummary->getTopRatedBuyingExperience());
        self::assertNull($itemSummary->getTyreLabelImageUrl());
        self::assertNull($itemSummary->getUnitPrice());
        self::assertNull($itemSummary->getUnitPricingMeasure());
        self::assertNull($itemSummary->getWatchCount());

        self::assertSame($itemSummary, $itemSummary->setAdditionalImages($additionalImages));
        self::assertSame($itemSummary, $itemSummary->setAdultOnly(false));
        self::assertSame($itemSummary, $itemSummary->setAvailableCoupons(false));
        self::assertSame($itemSummary, $itemSummary->setBidCount(42));
        self::assertSame($itemSummary, $itemSummary->setBuyingOptions($buyingOptions));
        self::assertSame($itemSummary, $itemSummary->setCategories($categories));
        self::assertSame($itemSummary, $itemSummary->setCompatibilityMatch('val_compatibilityMatch'));
        self::assertSame($itemSummary, $itemSummary->setCompatibilityProperties($compatibilityProperties));
        self::assertSame($itemSummary, $itemSummary->setCondition('val_condition'));
        self::assertSame($itemSummary, $itemSummary->setConditionId('val_conditionId'));
        self::assertSame($itemSummary, $itemSummary->setCurrentBidPrice($currentBidPrice));
        self::assertSame($itemSummary, $itemSummary->setDistanceFromPickupLocation($distanceFromPickupLocation));
        self::assertSame($itemSummary, $itemSummary->setEnergyEfficiencyClass('val_energyEfficiencyClass'));
        self::assertSame($itemSummary, $itemSummary->setEpid('val_epid'));
        self::assertSame($itemSummary, $itemSummary->setImage($image));
        self::assertSame($itemSummary, $itemSummary->setItemAffiliateWebUrl('val_itemAffiliateWebUrl'));
        self::assertSame($itemSummary, $itemSummary->setItemCreationDate(42));
        self::assertSame($itemSummary, $itemSummary->setItemEndDate(42));
        self::assertSame($itemSummary, $itemSummary->setItemGroupHref('val_itemGroupHref'));
        self::assertSame($itemSummary, $itemSummary->setItemGroupType('val_itemGroupType'));
        self::assertSame($itemSummary, $itemSummary->setItemHref('val_itemHref'));
        self::assertSame($itemSummary, $itemSummary->setItemId('val_itemId'));
        self::assertSame($itemSummary, $itemSummary->setItemLocation($itemLocation));
        self::assertSame($itemSummary, $itemSummary->setItemOriginDate(42));
        self::assertSame($itemSummary, $itemSummary->setItemWebUrl('val_itemWebUrl'));
        self::assertSame($itemSummary, $itemSummary->setLeafCategoryIds($leafCategoryIds));
        self::assertSame($itemSummary, $itemSummary->setLegacyItemId('val_legacyItemId'));
        self::assertSame($itemSummary, $itemSummary->setListingMarketplaceId('val_listingMarketplaceId'));
        self::assertSame($itemSummary, $itemSummary->setMarketingPrice($marketingPrice));
        self::assertSame($itemSummary, $itemSummary->setPickupOptions($pickupOptions));
        self::assertSame($itemSummary, $itemSummary->setPrice($price));
        self::assertSame($itemSummary, $itemSummary->setPriceDisplayCondition('val_priceDisplayCondition'));
        self::assertSame($itemSummary, $itemSummary->setPriorityListing(false));
        self::assertSame($itemSummary, $itemSummary->setQualifiedPrograms($qualifiedPrograms));
        self::assertSame($itemSummary, $itemSummary->setSeller($seller));
        self::assertSame($itemSummary, $itemSummary->setShippingOptions($shippingOptions));
        self::assertSame($itemSummary, $itemSummary->setShortDescription('val_shortDescription'));
        self::assertSame($itemSummary, $itemSummary->setThumbnailImages($thumbnailImages));
        self::assertSame($itemSummary, $itemSummary->setTitle('val_title'));
        self::assertSame($itemSummary, $itemSummary->setTopRatedBuyingExperience(false));
        self::assertSame($itemSummary, $itemSummary->setTyreLabelImageUrl('val_tyreLabelImageUrl'));
        self::assertSame($itemSummary, $itemSummary->setUnitPrice($unitPrice));
        self::assertSame($itemSummary, $itemSummary->setUnitPricingMeasure('val_unitPricingMeasure'));
        self::assertSame($itemSummary, $itemSummary->setWatchCount(42));

        self::assertSame($additionalImages, $itemSummary->getAdditionalImages());
        self::assertFalse($itemSummary->getAdultOnly());
        self::assertFalse($itemSummary->getAvailableCoupons());
        self::assertSame(42, $itemSummary->getBidCount());
        self::assertSame($buyingOptions, $itemSummary->getBuyingOptions());
        self::assertSame($categories, $itemSummary->getCategories());
        self::assertSame('val_compatibilityMatch', $itemSummary->getCompatibilityMatch());
        self::assertSame($compatibilityProperties, $itemSummary->getCompatibilityProperties());
        self::assertSame('val_condition', $itemSummary->getCondition());
        self::assertSame('val_conditionId', $itemSummary->getConditionId());
        self::assertSame($currentBidPrice, $itemSummary->getCurrentBidPrice());
        self::assertSame($distanceFromPickupLocation, $itemSummary->getDistanceFromPickupLocation());
        self::assertSame('val_energyEfficiencyClass', $itemSummary->getEnergyEfficiencyClass());
        self::assertSame('val_epid', $itemSummary->getEpid());
        self::assertSame($image, $itemSummary->getImage());
        self::assertSame('val_itemAffiliateWebUrl', $itemSummary->getItemAffiliateWebUrl());
        self::assertSame(42, $itemSummary->getItemCreationDate());
        self::assertSame(42, $itemSummary->getItemEndDate());
        self::assertSame('val_itemGroupHref', $itemSummary->getItemGroupHref());
        self::assertSame('val_itemGroupType', $itemSummary->getItemGroupType());
        self::assertSame('val_itemHref', $itemSummary->getItemHref());
        self::assertSame('val_itemId', $itemSummary->getItemId());
        self::assertSame($itemLocation, $itemSummary->getItemLocation());
        self::assertSame(42, $itemSummary->getItemOriginDate());
        self::assertSame('val_itemWebUrl', $itemSummary->getItemWebUrl());
        self::assertSame($leafCategoryIds, $itemSummary->getLeafCategoryIds());
        self::assertSame('val_legacyItemId', $itemSummary->getLegacyItemId());
        self::assertSame('val_listingMarketplaceId', $itemSummary->getListingMarketplaceId());
        self::assertSame($marketingPrice, $itemSummary->getMarketingPrice());
        self::assertSame($pickupOptions, $itemSummary->getPickupOptions());
        self::assertSame($price, $itemSummary->getPrice());
        self::assertSame('val_priceDisplayCondition', $itemSummary->getPriceDisplayCondition());
        self::assertFalse($itemSummary->getPriorityListing());
        self::assertSame($qualifiedPrograms, $itemSummary->getQualifiedPrograms());
        self::assertSame($seller, $itemSummary->getSeller());
        self::assertSame($shippingOptions, $itemSummary->getShippingOptions());
        self::assertSame('val_shortDescription', $itemSummary->getShortDescription());
        self::assertSame($thumbnailImages, $itemSummary->getThumbnailImages());
        self::assertSame('val_title', $itemSummary->getTitle());
        self::assertFalse($itemSummary->getTopRatedBuyingExperience());
        self::assertSame('val_tyreLabelImageUrl', $itemSummary->getTyreLabelImageUrl());
        self::assertSame($unitPrice, $itemSummary->getUnitPrice());
        self::assertSame('val_unitPricingMeasure', $itemSummary->getUnitPricingMeasure());
        self::assertSame(42, $itemSummary->getWatchCount());
    }
}
