<?php

declare(strict_types=1);

namespace ChristianBrown\EBay\Browse\Tests\Model;

use ChristianBrown\EBay\Browse\Model\ConvertedAmountInterface;
use ChristianBrown\EBay\Browse\Model\ErrorInterface;
use ChristianBrown\EBay\Browse\Model\EstimatedAvailabilityInterface;
use ChristianBrown\EBay\Browse\Model\ImageInterface;
use ChristianBrown\EBay\Browse\Model\Item;
use ChristianBrown\EBay\Browse\Model\ItemLocationInterface;
use ChristianBrown\EBay\Browse\Model\MarketingPriceInterface;
use ChristianBrown\EBay\Browse\Model\PaymentMethodInterface;
use ChristianBrown\EBay\Browse\Model\ProductInterface;
use ChristianBrown\EBay\Browse\Model\ReturnTermsInterface;
use ChristianBrown\EBay\Browse\Model\SellerInterface;
use ChristianBrown\EBay\Browse\Model\ShippingOptionInterface;
use ChristianBrown\EBay\Browse\Model\ShipToLocationsInterface;
use ChristianBrown\EBay\Browse\Model\TypedNameValueInterface;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(Item::class)]
final class ItemTest extends TestCase
{
    public function test(): void
    {
        $additionalImages = [self::createStub(ImageInterface::class)];
        $currentBidPrice = self::createStub(ConvertedAmountInterface::class);
        $estimatedAvailabilities = [self::createStub(EstimatedAvailabilityInterface::class)];
        $image = self::createStub(ImageInterface::class);
        $itemLocation = self::createStub(ItemLocationInterface::class);
        $localizedAspects = [self::createStub(TypedNameValueInterface::class)];
        $marketingPrice = self::createStub(MarketingPriceInterface::class);
        $paymentMethods = [self::createStub(PaymentMethodInterface::class)];
        $price = self::createStub(ConvertedAmountInterface::class);
        $product = self::createStub(ProductInterface::class);
        $returnTerms = self::createStub(ReturnTermsInterface::class);
        $seller = self::createStub(SellerInterface::class);
        $shipToLocations = self::createStub(ShipToLocationsInterface::class);
        $shippingOptions = [self::createStub(ShippingOptionInterface::class)];
        $unitPrice = self::createStub(ConvertedAmountInterface::class);
        $warnings = [self::createStub(ErrorInterface::class)];

        $item = new Item('v_0');
        self::assertSame([], $item->getAdditionalImages());
        self::assertNull($item->getAdultOnly());
        self::assertNull($item->getAgeGroup());
        self::assertNull($item->getBidCount());
        self::assertNull($item->getBrand());
        self::assertSame([], $item->getBuyingOptions());
        self::assertNull($item->getCategoryId());
        self::assertNull($item->getCategoryIdPath());
        self::assertNull($item->getCategoryPath());
        self::assertNull($item->getColor());
        self::assertNull($item->getCondition());
        self::assertNull($item->getConditionDescription());
        self::assertNull($item->getConditionId());
        self::assertNull($item->getCurrentBidPrice());
        self::assertNull($item->getDescription());
        self::assertNull($item->getEligibleForInlineCheckout());
        self::assertNull($item->getEnabledForGuestCheckout());
        self::assertNull($item->getEnergyEfficiencyClass());
        self::assertNull($item->getEpid());
        self::assertSame([], $item->getEstimatedAvailabilities());
        self::assertNull($item->getGtin());
        self::assertNull($item->getImage());
        self::assertNull($item->getImmediatePay());
        self::assertNull($item->getItemAffiliateWebUrl());
        self::assertNull($item->getItemCreationDate());
        self::assertNull($item->getItemEndDate());
        self::assertSame('v_0', $item->getItemId());
        self::assertNull($item->getItemLocation());
        self::assertNull($item->getItemWebUrl());
        self::assertNull($item->getLegacyItemId());
        self::assertNull($item->getListingMarketplaceId());
        self::assertSame([], $item->getLocalizedAspects());
        self::assertNull($item->getLotSize());
        self::assertNull($item->getMarketingPrice());
        self::assertNull($item->getMaterial());
        self::assertNull($item->getMpn());
        self::assertSame([], $item->getPaymentMethods());
        self::assertNull($item->getPrice());
        self::assertNull($item->getPriorityListing());
        self::assertNull($item->getProduct());
        self::assertNull($item->getReturnTerms());
        self::assertNull($item->getSeller());
        self::assertNull($item->getSellerItemRevision());
        self::assertNull($item->getShipToLocations());
        self::assertSame([], $item->getShippingOptions());
        self::assertNull($item->getShortDescription());
        self::assertNull($item->getSubtitle());
        self::assertNull($item->getTitle());
        self::assertNull($item->getTopRatedBuyingExperience());
        self::assertNull($item->getUniqueBidderCount());
        self::assertNull($item->getUnitPrice());
        self::assertNull($item->getUnitPricingMeasure());
        self::assertSame([], $item->getWarnings());

        self::assertSame($item, $item->setAdditionalImages($additionalImages));
        self::assertSame($item, $item->setAdultOnly(false));
        self::assertSame($item, $item->setAgeGroup('v_53'));
        self::assertSame($item, $item->setBidCount(154));
        self::assertSame($item, $item->setBrand('v_55'));
        self::assertSame($item, $item->setBuyingOptions(['s_56']));
        self::assertSame($item, $item->setCategoryId('v_57'));
        self::assertSame($item, $item->setCategoryIdPath('v_58'));
        self::assertSame($item, $item->setCategoryPath('v_59'));
        self::assertSame($item, $item->setColor('v_60'));
        self::assertSame($item, $item->setCondition('v_61'));
        self::assertSame($item, $item->setConditionDescription('v_62'));
        self::assertSame($item, $item->setConditionId('v_63'));
        self::assertSame($item, $item->setCurrentBidPrice($currentBidPrice));
        self::assertSame($item, $item->setDescription('v_65'));
        self::assertSame($item, $item->setEligibleForInlineCheckout(false));
        self::assertSame($item, $item->setEnabledForGuestCheckout(false));
        self::assertSame($item, $item->setEnergyEfficiencyClass('v_68'));
        self::assertSame($item, $item->setEpid('v_69'));
        self::assertSame($item, $item->setEstimatedAvailabilities($estimatedAvailabilities));
        self::assertSame($item, $item->setGtin('v_71'));
        self::assertSame($item, $item->setImage($image));
        self::assertSame($item, $item->setImmediatePay(false));
        self::assertSame($item, $item->setItemAffiliateWebUrl('v_74'));
        self::assertSame($item, $item->setItemCreationDate(1700000075));
        self::assertSame($item, $item->setItemEndDate(1700000076));
        self::assertSame($item, $item->setItemId('v_77'));
        self::assertSame($item, $item->setItemLocation($itemLocation));
        self::assertSame($item, $item->setItemWebUrl('v_79'));
        self::assertSame($item, $item->setLegacyItemId('v_80'));
        self::assertSame($item, $item->setListingMarketplaceId('v_81'));
        self::assertSame($item, $item->setLocalizedAspects($localizedAspects));
        self::assertSame($item, $item->setLotSize(183));
        self::assertSame($item, $item->setMarketingPrice($marketingPrice));
        self::assertSame($item, $item->setMaterial('v_85'));
        self::assertSame($item, $item->setMpn('v_86'));
        self::assertSame($item, $item->setPaymentMethods($paymentMethods));
        self::assertSame($item, $item->setPrice($price));
        self::assertSame($item, $item->setPriorityListing(false));
        self::assertSame($item, $item->setProduct($product));
        self::assertSame($item, $item->setReturnTerms($returnTerms));
        self::assertSame($item, $item->setSeller($seller));
        self::assertSame($item, $item->setSellerItemRevision('v_93'));
        self::assertSame($item, $item->setShipToLocations($shipToLocations));
        self::assertSame($item, $item->setShippingOptions($shippingOptions));
        self::assertSame($item, $item->setShortDescription('v_96'));
        self::assertSame($item, $item->setSubtitle('v_97'));
        self::assertSame($item, $item->setTitle('v_98'));
        self::assertSame($item, $item->setTopRatedBuyingExperience(false));
        self::assertSame($item, $item->setUniqueBidderCount(200));
        self::assertSame($item, $item->setUnitPrice($unitPrice));
        self::assertSame($item, $item->setUnitPricingMeasure('v_102'));
        self::assertSame($item, $item->setWarnings($warnings));

        self::assertSame($additionalImages, $item->getAdditionalImages());
        self::assertFalse($item->getAdultOnly());
        self::assertSame('v_53', $item->getAgeGroup());
        self::assertSame(154, $item->getBidCount());
        self::assertSame('v_55', $item->getBrand());
        self::assertSame(['s_56'], $item->getBuyingOptions());
        self::assertSame('v_57', $item->getCategoryId());
        self::assertSame('v_58', $item->getCategoryIdPath());
        self::assertSame('v_59', $item->getCategoryPath());
        self::assertSame('v_60', $item->getColor());
        self::assertSame('v_61', $item->getCondition());
        self::assertSame('v_62', $item->getConditionDescription());
        self::assertSame('v_63', $item->getConditionId());
        self::assertSame($currentBidPrice, $item->getCurrentBidPrice());
        self::assertSame('v_65', $item->getDescription());
        self::assertFalse($item->getEligibleForInlineCheckout());
        self::assertFalse($item->getEnabledForGuestCheckout());
        self::assertSame('v_68', $item->getEnergyEfficiencyClass());
        self::assertSame('v_69', $item->getEpid());
        self::assertSame($estimatedAvailabilities, $item->getEstimatedAvailabilities());
        self::assertSame('v_71', $item->getGtin());
        self::assertSame($image, $item->getImage());
        self::assertFalse($item->getImmediatePay());
        self::assertSame('v_74', $item->getItemAffiliateWebUrl());
        self::assertSame(1700000075, $item->getItemCreationDate());
        self::assertSame(1700000076, $item->getItemEndDate());
        self::assertSame('v_77', $item->getItemId());
        self::assertSame($itemLocation, $item->getItemLocation());
        self::assertSame('v_79', $item->getItemWebUrl());
        self::assertSame('v_80', $item->getLegacyItemId());
        self::assertSame('v_81', $item->getListingMarketplaceId());
        self::assertSame($localizedAspects, $item->getLocalizedAspects());
        self::assertSame(183, $item->getLotSize());
        self::assertSame($marketingPrice, $item->getMarketingPrice());
        self::assertSame('v_85', $item->getMaterial());
        self::assertSame('v_86', $item->getMpn());
        self::assertSame($paymentMethods, $item->getPaymentMethods());
        self::assertSame($price, $item->getPrice());
        self::assertFalse($item->getPriorityListing());
        self::assertSame($product, $item->getProduct());
        self::assertSame($returnTerms, $item->getReturnTerms());
        self::assertSame($seller, $item->getSeller());
        self::assertSame('v_93', $item->getSellerItemRevision());
        self::assertSame($shipToLocations, $item->getShipToLocations());
        self::assertSame($shippingOptions, $item->getShippingOptions());
        self::assertSame('v_96', $item->getShortDescription());
        self::assertSame('v_97', $item->getSubtitle());
        self::assertSame('v_98', $item->getTitle());
        self::assertFalse($item->getTopRatedBuyingExperience());
        self::assertSame(200, $item->getUniqueBidderCount());
        self::assertSame($unitPrice, $item->getUnitPrice());
        self::assertSame('v_102', $item->getUnitPricingMeasure());
        self::assertSame($warnings, $item->getWarnings());
    }
}
