<?php

declare(strict_types=1);

namespace ChristianBrown\EBay\Browse\Tests\Model;

use ChristianBrown\EBay\Browse\Model\AddonServiceInterface;
use ChristianBrown\EBay\Browse\Model\AuthenticityGuaranteeProgramInterface;
use ChristianBrown\EBay\Browse\Model\AuthenticityVerificationProgramInterface;
use ChristianBrown\EBay\Browse\Model\AvailableCouponInterface;
use ChristianBrown\EBay\Browse\Model\CompanyAddressInterface;
use ChristianBrown\EBay\Browse\Model\ConditionDescriptorInterface;
use ChristianBrown\EBay\Browse\Model\ConvertedAmountInterface;
use ChristianBrown\EBay\Browse\Model\ErrorInterface;
use ChristianBrown\EBay\Browse\Model\EstimatedAvailabilityInterface;
use ChristianBrown\EBay\Browse\Model\HazardousMaterialsLabelsInterface;
use ChristianBrown\EBay\Browse\Model\ImageInterface;
use ChristianBrown\EBay\Browse\Model\Item;
use ChristianBrown\EBay\Browse\Model\ItemCharityTermsInterface;
use ChristianBrown\EBay\Browse\Model\ItemGroupSummaryInterface;
use ChristianBrown\EBay\Browse\Model\ItemLocationInterface;
use ChristianBrown\EBay\Browse\Model\MarketingPriceInterface;
use ChristianBrown\EBay\Browse\Model\PaymentMethodInterface;
use ChristianBrown\EBay\Browse\Model\ProductInterface;
use ChristianBrown\EBay\Browse\Model\ProductSafetyLabelsInterface;
use ChristianBrown\EBay\Browse\Model\ResponsiblePersonInterface;
use ChristianBrown\EBay\Browse\Model\ReturnTermsInterface;
use ChristianBrown\EBay\Browse\Model\ReviewRatingInterface;
use ChristianBrown\EBay\Browse\Model\SellerCustomPolicyInterface;
use ChristianBrown\EBay\Browse\Model\SellerInterface;
use ChristianBrown\EBay\Browse\Model\ShippingOptionInterface;
use ChristianBrown\EBay\Browse\Model\ShipToLocationsInterface;
use ChristianBrown\EBay\Browse\Model\TaxInterface;
use ChristianBrown\EBay\Browse\Model\TypedNameValueInterface;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(Item::class)]
final class ItemTest extends TestCase
{
    public function test(): void
    {
        $additionalImages = [self::createStub(ImageInterface::class)];
        $addonServices = [self::createStub(AddonServiceInterface::class)];
        $authenticityGuarantee = self::createStub(AuthenticityGuaranteeProgramInterface::class);
        $authenticityVerification = self::createStub(AuthenticityVerificationProgramInterface::class);
        $availableCoupons = [self::createStub(AvailableCouponInterface::class)];
        $buyingOptions = ['s'];
        $charityTerms = self::createStub(ItemCharityTermsInterface::class);
        $conditionDescriptors = [self::createStub(ConditionDescriptorInterface::class)];
        $currentBidPrice = self::createStub(ConvertedAmountInterface::class);
        $ecoParticipationFee = self::createStub(ConvertedAmountInterface::class);
        $estimatedAvailabilities = [self::createStub(EstimatedAvailabilityInterface::class)];
        $hazardousMaterialsLabels = self::createStub(HazardousMaterialsLabelsInterface::class);
        $image = self::createStub(ImageInterface::class);
        $itemLocation = self::createStub(ItemLocationInterface::class);
        $localizedAspects = [self::createStub(TypedNameValueInterface::class)];
        $manufacturer = self::createStub(CompanyAddressInterface::class);
        $marketingPrice = self::createStub(MarketingPriceInterface::class);
        $minimumPriceToBid = self::createStub(ConvertedAmountInterface::class);
        $paymentMethods = [self::createStub(PaymentMethodInterface::class)];
        $price = self::createStub(ConvertedAmountInterface::class);
        $primaryItemGroup = self::createStub(ItemGroupSummaryInterface::class);
        $primaryProductReviewRating = self::createStub(ReviewRatingInterface::class);
        $product = self::createStub(ProductInterface::class);
        $productSafetyLabels = self::createStub(ProductSafetyLabelsInterface::class);
        $qualifiedPrograms = ['s'];
        $responsiblePersons = [self::createStub(ResponsiblePersonInterface::class)];
        $returnTerms = self::createStub(ReturnTermsInterface::class);
        $seller = self::createStub(SellerInterface::class);
        $sellerCustomPolicies = [self::createStub(SellerCustomPolicyInterface::class)];
        $shippingOptions = [self::createStub(ShippingOptionInterface::class)];
        $shipToLocations = self::createStub(ShipToLocationsInterface::class);
        $taxes = [self::createStub(TaxInterface::class)];
        $unitPrice = self::createStub(ConvertedAmountInterface::class);
        $warnings = [self::createStub(ErrorInterface::class)];

        $item = new Item('val_itemId');
        self::assertSame('val_itemId', $item->getItemId());
        self::assertSame([], $item->getAdditionalImages());
        self::assertSame([], $item->getAddonServices());
        self::assertNull($item->getAdultOnly());
        self::assertNull($item->getAgeGroup());
        self::assertNull($item->getAuthenticityGuarantee());
        self::assertNull($item->getAuthenticityVerification());
        self::assertSame([], $item->getAvailableCoupons());
        self::assertNull($item->getBidCount());
        self::assertNull($item->getBrand());
        self::assertSame([], $item->getBuyingOptions());
        self::assertNull($item->getCategoryId());
        self::assertNull($item->getCategoryIdPath());
        self::assertNull($item->getCategoryPath());
        self::assertNull($item->getCharityTerms());
        self::assertNull($item->getColor());
        self::assertNull($item->getCondition());
        self::assertNull($item->getConditionDescription());
        self::assertSame([], $item->getConditionDescriptors());
        self::assertNull($item->getConditionId());
        self::assertNull($item->getCurrentBidPrice());
        self::assertNull($item->getDescription());
        self::assertNull($item->getEcoParticipationFee());
        self::assertNull($item->getEligibleForInlineCheckout());
        self::assertNull($item->getEnabledForGuestCheckout());
        self::assertNull($item->getEnergyEfficiencyClass());
        self::assertNull($item->getEpid());
        self::assertSame([], $item->getEstimatedAvailabilities());
        self::assertNull($item->getGender());
        self::assertNull($item->getGtin());
        self::assertNull($item->getHazardousMaterialsLabels());
        self::assertNull($item->getImage());
        self::assertNull($item->getImmediatePay());
        self::assertNull($item->getInferredEpid());
        self::assertNull($item->getItemAffiliateWebUrl());
        self::assertNull($item->getItemCreationDate());
        self::assertNull($item->getItemEndDate());
        self::assertNull($item->getItemLocation());
        self::assertNull($item->getItemWebUrl());
        self::assertNull($item->getLegacyItemId());
        self::assertNull($item->getListingMarketplaceId());
        self::assertSame([], $item->getLocalizedAspects());
        self::assertNull($item->getLotSize());
        self::assertNull($item->getManufacturer());
        self::assertNull($item->getMarketingPrice());
        self::assertNull($item->getMaterial());
        self::assertNull($item->getMinimumPriceToBid());
        self::assertNull($item->getMpn());
        self::assertNull($item->getPattern());
        self::assertSame([], $item->getPaymentMethods());
        self::assertNull($item->getPrice());
        self::assertNull($item->getPriceDisplayCondition());
        self::assertNull($item->getPrimaryItemGroup());
        self::assertNull($item->getPrimaryProductReviewRating());
        self::assertNull($item->getPriorityListing());
        self::assertNull($item->getProduct());
        self::assertNull($item->getProductFicheWebUrl());
        self::assertNull($item->getProductSafetyLabels());
        self::assertSame([], $item->getQualifiedPrograms());
        self::assertNull($item->getQuantityLimitPerBuyer());
        self::assertNull($item->getRepairScore());
        self::assertNull($item->getReservePriceMet());
        self::assertSame([], $item->getResponsiblePersons());
        self::assertNull($item->getReturnTerms());
        self::assertNull($item->getSeller());
        self::assertSame([], $item->getSellerCustomPolicies());
        self::assertNull($item->getSellerItemRevision());
        self::assertSame([], $item->getShippingOptions());
        self::assertNull($item->getShipToLocations());
        self::assertNull($item->getShortDescription());
        self::assertNull($item->getSize());
        self::assertNull($item->getSizeSystem());
        self::assertNull($item->getSizeType());
        self::assertNull($item->getSubtitle());
        self::assertSame([], $item->getTaxes());
        self::assertNull($item->getTitle());
        self::assertNull($item->getTopRatedBuyingExperience());
        self::assertNull($item->getTyreLabelImageUrl());
        self::assertNull($item->getUniqueBidderCount());
        self::assertNull($item->getUnitPrice());
        self::assertNull($item->getUnitPricingMeasure());
        self::assertSame([], $item->getWarnings());
        self::assertNull($item->getWatchCount());

        self::assertSame($item, $item->setAdditionalImages($additionalImages));
        self::assertSame($item, $item->setAddonServices($addonServices));
        self::assertSame($item, $item->setAdultOnly(false));
        self::assertSame($item, $item->setAgeGroup('val_ageGroup'));
        self::assertSame($item, $item->setAuthenticityGuarantee($authenticityGuarantee));
        self::assertSame($item, $item->setAuthenticityVerification($authenticityVerification));
        self::assertSame($item, $item->setAvailableCoupons($availableCoupons));
        self::assertSame($item, $item->setBidCount(42));
        self::assertSame($item, $item->setBrand('val_brand'));
        self::assertSame($item, $item->setBuyingOptions($buyingOptions));
        self::assertSame($item, $item->setCategoryId('val_categoryId'));
        self::assertSame($item, $item->setCategoryIdPath('val_categoryIdPath'));
        self::assertSame($item, $item->setCategoryPath('val_categoryPath'));
        self::assertSame($item, $item->setCharityTerms($charityTerms));
        self::assertSame($item, $item->setColor('val_color'));
        self::assertSame($item, $item->setCondition('val_condition'));
        self::assertSame($item, $item->setConditionDescription('val_conditionDescription'));
        self::assertSame($item, $item->setConditionDescriptors($conditionDescriptors));
        self::assertSame($item, $item->setConditionId('val_conditionId'));
        self::assertSame($item, $item->setCurrentBidPrice($currentBidPrice));
        self::assertSame($item, $item->setDescription('val_description'));
        self::assertSame($item, $item->setEcoParticipationFee($ecoParticipationFee));
        self::assertSame($item, $item->setEligibleForInlineCheckout(false));
        self::assertSame($item, $item->setEnabledForGuestCheckout(false));
        self::assertSame($item, $item->setEnergyEfficiencyClass('val_energyEfficiencyClass'));
        self::assertSame($item, $item->setEpid('val_epid'));
        self::assertSame($item, $item->setEstimatedAvailabilities($estimatedAvailabilities));
        self::assertSame($item, $item->setGender('val_gender'));
        self::assertSame($item, $item->setGtin('val_gtin'));
        self::assertSame($item, $item->setHazardousMaterialsLabels($hazardousMaterialsLabels));
        self::assertSame($item, $item->setImage($image));
        self::assertSame($item, $item->setImmediatePay(false));
        self::assertSame($item, $item->setInferredEpid('val_inferredEpid'));
        self::assertSame($item, $item->setItemAffiliateWebUrl('val_itemAffiliateWebUrl'));
        self::assertSame($item, $item->setItemCreationDate(42));
        self::assertSame($item, $item->setItemEndDate(42));
        self::assertSame($item, $item->setItemId('val_itemId'));
        self::assertSame($item, $item->setItemLocation($itemLocation));
        self::assertSame($item, $item->setItemWebUrl('val_itemWebUrl'));
        self::assertSame($item, $item->setLegacyItemId('val_legacyItemId'));
        self::assertSame($item, $item->setListingMarketplaceId('val_listingMarketplaceId'));
        self::assertSame($item, $item->setLocalizedAspects($localizedAspects));
        self::assertSame($item, $item->setLotSize(42));
        self::assertSame($item, $item->setManufacturer($manufacturer));
        self::assertSame($item, $item->setMarketingPrice($marketingPrice));
        self::assertSame($item, $item->setMaterial('val_material'));
        self::assertSame($item, $item->setMinimumPriceToBid($minimumPriceToBid));
        self::assertSame($item, $item->setMpn('val_mpn'));
        self::assertSame($item, $item->setPattern('val_pattern'));
        self::assertSame($item, $item->setPaymentMethods($paymentMethods));
        self::assertSame($item, $item->setPrice($price));
        self::assertSame($item, $item->setPriceDisplayCondition('val_priceDisplayCondition'));
        self::assertSame($item, $item->setPrimaryItemGroup($primaryItemGroup));
        self::assertSame($item, $item->setPrimaryProductReviewRating($primaryProductReviewRating));
        self::assertSame($item, $item->setPriorityListing(false));
        self::assertSame($item, $item->setProduct($product));
        self::assertSame($item, $item->setProductFicheWebUrl('val_productFicheWebUrl'));
        self::assertSame($item, $item->setProductSafetyLabels($productSafetyLabels));
        self::assertSame($item, $item->setQualifiedPrograms($qualifiedPrograms));
        self::assertSame($item, $item->setQuantityLimitPerBuyer(42));
        self::assertSame($item, $item->setRepairScore('val_repairScore'));
        self::assertSame($item, $item->setReservePriceMet(false));
        self::assertSame($item, $item->setResponsiblePersons($responsiblePersons));
        self::assertSame($item, $item->setReturnTerms($returnTerms));
        self::assertSame($item, $item->setSeller($seller));
        self::assertSame($item, $item->setSellerCustomPolicies($sellerCustomPolicies));
        self::assertSame($item, $item->setSellerItemRevision('val_sellerItemRevision'));
        self::assertSame($item, $item->setShippingOptions($shippingOptions));
        self::assertSame($item, $item->setShipToLocations($shipToLocations));
        self::assertSame($item, $item->setShortDescription('val_shortDescription'));
        self::assertSame($item, $item->setSize('val_size'));
        self::assertSame($item, $item->setSizeSystem('val_sizeSystem'));
        self::assertSame($item, $item->setSizeType('val_sizeType'));
        self::assertSame($item, $item->setSubtitle('val_subtitle'));
        self::assertSame($item, $item->setTaxes($taxes));
        self::assertSame($item, $item->setTitle('val_title'));
        self::assertSame($item, $item->setTopRatedBuyingExperience(false));
        self::assertSame($item, $item->setTyreLabelImageUrl('val_tyreLabelImageUrl'));
        self::assertSame($item, $item->setUniqueBidderCount(42));
        self::assertSame($item, $item->setUnitPrice($unitPrice));
        self::assertSame($item, $item->setUnitPricingMeasure('val_unitPricingMeasure'));
        self::assertSame($item, $item->setWarnings($warnings));
        self::assertSame($item, $item->setWatchCount(42));

        self::assertSame($additionalImages, $item->getAdditionalImages());
        self::assertSame($addonServices, $item->getAddonServices());
        self::assertFalse($item->getAdultOnly());
        self::assertSame('val_ageGroup', $item->getAgeGroup());
        self::assertSame($authenticityGuarantee, $item->getAuthenticityGuarantee());
        self::assertSame($authenticityVerification, $item->getAuthenticityVerification());
        self::assertSame($availableCoupons, $item->getAvailableCoupons());
        self::assertSame(42, $item->getBidCount());
        self::assertSame('val_brand', $item->getBrand());
        self::assertSame($buyingOptions, $item->getBuyingOptions());
        self::assertSame('val_categoryId', $item->getCategoryId());
        self::assertSame('val_categoryIdPath', $item->getCategoryIdPath());
        self::assertSame('val_categoryPath', $item->getCategoryPath());
        self::assertSame($charityTerms, $item->getCharityTerms());
        self::assertSame('val_color', $item->getColor());
        self::assertSame('val_condition', $item->getCondition());
        self::assertSame('val_conditionDescription', $item->getConditionDescription());
        self::assertSame($conditionDescriptors, $item->getConditionDescriptors());
        self::assertSame('val_conditionId', $item->getConditionId());
        self::assertSame($currentBidPrice, $item->getCurrentBidPrice());
        self::assertSame('val_description', $item->getDescription());
        self::assertSame($ecoParticipationFee, $item->getEcoParticipationFee());
        self::assertFalse($item->getEligibleForInlineCheckout());
        self::assertFalse($item->getEnabledForGuestCheckout());
        self::assertSame('val_energyEfficiencyClass', $item->getEnergyEfficiencyClass());
        self::assertSame('val_epid', $item->getEpid());
        self::assertSame($estimatedAvailabilities, $item->getEstimatedAvailabilities());
        self::assertSame('val_gender', $item->getGender());
        self::assertSame('val_gtin', $item->getGtin());
        self::assertSame($hazardousMaterialsLabels, $item->getHazardousMaterialsLabels());
        self::assertSame($image, $item->getImage());
        self::assertFalse($item->getImmediatePay());
        self::assertSame('val_inferredEpid', $item->getInferredEpid());
        self::assertSame('val_itemAffiliateWebUrl', $item->getItemAffiliateWebUrl());
        self::assertSame(42, $item->getItemCreationDate());
        self::assertSame(42, $item->getItemEndDate());
        self::assertSame('val_itemId', $item->getItemId());
        self::assertSame($itemLocation, $item->getItemLocation());
        self::assertSame('val_itemWebUrl', $item->getItemWebUrl());
        self::assertSame('val_legacyItemId', $item->getLegacyItemId());
        self::assertSame('val_listingMarketplaceId', $item->getListingMarketplaceId());
        self::assertSame($localizedAspects, $item->getLocalizedAspects());
        self::assertSame(42, $item->getLotSize());
        self::assertSame($manufacturer, $item->getManufacturer());
        self::assertSame($marketingPrice, $item->getMarketingPrice());
        self::assertSame('val_material', $item->getMaterial());
        self::assertSame($minimumPriceToBid, $item->getMinimumPriceToBid());
        self::assertSame('val_mpn', $item->getMpn());
        self::assertSame('val_pattern', $item->getPattern());
        self::assertSame($paymentMethods, $item->getPaymentMethods());
        self::assertSame($price, $item->getPrice());
        self::assertSame('val_priceDisplayCondition', $item->getPriceDisplayCondition());
        self::assertSame($primaryItemGroup, $item->getPrimaryItemGroup());
        self::assertSame($primaryProductReviewRating, $item->getPrimaryProductReviewRating());
        self::assertFalse($item->getPriorityListing());
        self::assertSame($product, $item->getProduct());
        self::assertSame('val_productFicheWebUrl', $item->getProductFicheWebUrl());
        self::assertSame($productSafetyLabels, $item->getProductSafetyLabels());
        self::assertSame($qualifiedPrograms, $item->getQualifiedPrograms());
        self::assertSame(42, $item->getQuantityLimitPerBuyer());
        self::assertSame('val_repairScore', $item->getRepairScore());
        self::assertFalse($item->getReservePriceMet());
        self::assertSame($responsiblePersons, $item->getResponsiblePersons());
        self::assertSame($returnTerms, $item->getReturnTerms());
        self::assertSame($seller, $item->getSeller());
        self::assertSame($sellerCustomPolicies, $item->getSellerCustomPolicies());
        self::assertSame('val_sellerItemRevision', $item->getSellerItemRevision());
        self::assertSame($shippingOptions, $item->getShippingOptions());
        self::assertSame($shipToLocations, $item->getShipToLocations());
        self::assertSame('val_shortDescription', $item->getShortDescription());
        self::assertSame('val_size', $item->getSize());
        self::assertSame('val_sizeSystem', $item->getSizeSystem());
        self::assertSame('val_sizeType', $item->getSizeType());
        self::assertSame('val_subtitle', $item->getSubtitle());
        self::assertSame($taxes, $item->getTaxes());
        self::assertSame('val_title', $item->getTitle());
        self::assertFalse($item->getTopRatedBuyingExperience());
        self::assertSame('val_tyreLabelImageUrl', $item->getTyreLabelImageUrl());
        self::assertSame(42, $item->getUniqueBidderCount());
        self::assertSame($unitPrice, $item->getUnitPrice());
        self::assertSame('val_unitPricingMeasure', $item->getUnitPricingMeasure());
        self::assertSame($warnings, $item->getWarnings());
        self::assertSame(42, $item->getWatchCount());
    }
}
